### ISSUE TITLE
QA connman-reconnect.timer

### ISSUE THREAD

**Issue by gerroon** [konsulko/connman-reconnect#1]
Hi

I was looking for a way to remedy my disconnexts and found your script. Could you tell me what the timer ties to the rest of your setup? I do not see how it is related to the reconnect.sh in any way, nI do not know alot about Sytemd however I hope this is the solution.

thanks

**Comment by leon-anavi** [comment]
Hi @gerroon,

This script was created as a quick work around long ago. Systemd service connman-reconnect executes reconnect.sh. Please explore systemd documentation to get better understanding how it works.

Best regards, Leon
